# See https://github.com/netlify/netlify-cms/blob/master/example/config.yml
backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

# display_url: https://gatsbro.netlify.com # This url will display in the top-right of the CMS
media_library:
  name: uploadcare
  config:
    publicKey: a73a170cb5cdef662983
    multiple: false
    tabs: 'file camera url facebook gdrive'
    effects: 'crop,rotate,enhance,grayscale'
    imageShrink: '2000x2000'
    previewStep: true
    clearable: true

collections: # A list of collections the CMS should be able to edit
  - name: 'pages'
    label: 'Page'
    delete: false # Prevent users from deleting documents in this collection
    editor:
      preview: true
    files:
      - file: 'content/pages/contact.md'
        label: 'Kontakt'
        name: 'contact-page'
        fields:
          - {
              label: Template,
              name: template,
              widget: hidden,
              default: ContactPage,
            }
          - { label: Slug, name: slug, widget: hidden, default: 'contact' }
          - { label: Titulek, name: title, widget: string }
          - { label: Obsah, name: body, widget: markdown }
          - { label: Vedoucí sboru, name: boss, widget: text }
          - { label: Telefon, name: phone, widget: string }
          - { label: Emailová adresa, name: email, widget: string }

      - file: 'content/pages/home.md'
        label: 'Domovská stránka'
        name: 'home-page'
        fields:
          - {
              label: Template,
              name: template,
              widget: hidden,
              default: HomePage,
            }
          - { label: Slug, name: slug, widget: hidden, default: '' }
          - { label: Titulek, name: title, widget: string }
          - { label: Obrázek v hlavičce, name: featuredImage, widget: image }
          - { label: Podtitulek, name: subtitle, widget: markdown, required: false }
          - { label: Obsah, name: body, widget: markdown }
          - label: 'Accordion'
            name: 'accordion'
            widget: 'list'
            required: false
            fields:
              - { label: 'Title', name: 'title', widget: 'string' }
              - { label: Content, name: content, widget: text }

      - file: 'content/pages/concerts.md'
        label: 'Koncerty'
        name: 'concerts-page'
        fields:
          - {
              label: Template,
              name: template,
              widget: hidden,
              default: ConcertsPage,
            }
          - { label: Slug, name: slug, widget: hidden, default: 'contact' }
          - { label: Titulek, name: title, widget: string }
          - { label: Obrázek v hlavičce, name: featuredImage, widget: image }
          - label: 'Koncerty'
            name: 'concerts'
            widget: 'list'
            required: false
            fields:
              - { label: 'Název koncertu', name: 'title', widget: 'string' }
              - { label: 'Popis koncertu', name: 'description', widget: 'string' }

  - name: posts
    label: Naše fotky
    editor:
      preview: true
    folder: content/posts
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - { label: Template, name: template, widget: hidden, default: SinglePost }
      - { label: Titulek, name: title, widget: string }
      - { label: Datum / Pořadí, name: date, widget: date, format: 'YYYY-MM-DD' }
      - { label: Náhled textu na kartě, name: excerpt, widget: text }
      - { label: Obsah, name: body, widget: markdown }
      - label: "Galerie"
        name: "images"
        widget: "list"
        summary: '{{fields.image}}'
        fields:
          - {
              label: Obrázky, 
              name: gallery,
              widget: image,
              media_library: { 
                config: {
                  multiple: true,
                  previewStep: false
                } 
              }
          }