# See https://github.com/netlify/netlify-cms/blob/master/example/config.yml
backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

# display_url: https://gatsbro.netlify.com # This url will display in the top-right of the CMS
media_library:
  name: cloudinary
  config:
    cloud_name: dfhtw7uzk
    api_key: 841185415291831
    multiple: false
    max_files: 200
    default_transformations:
      - fetch_format: auto
        width: 800
        height: 600   
        quality: auto
        crop: crop

collections: # A list of collections the CMS should be able to edit
  - name: 'pages'
    label: 'Stránka'
    delete: false # Prevent users from deleting documents in this collection
    editor:
      preview: true
    files:
      - file: 'content/pages/contact.md'
        label: 'Kontakt'
        name: 'contact-page'
        fields:
          - {
              label: Template,
              name: template,
              widget: hidden,
              default: ContactPage,
            }
          - { label: Slug, name: slug, widget: hidden, default: 'kontakt' }
          - { label: Obsah, name: body, widget: markdown }
          - { label: Vedoucí sboru, name: boss, widget: text }
          - { label: Telefon, name: phone, widget: string }
          - { label: Emailová adresa, name: email, widget: string }

      - file: 'content/pages/home.md'
        label: 'Domovská stránka'
        name: 'home-page'
        fields:
          - {
              label: Template,
              name: template,
              widget: hidden,
              default: HomePage,
            }
          - { label: Slug, name: slug, widget: hidden, default: '' }
          - { label: Titulek, name: title, widget: string }
          - label: Obrázek v hlavičce, 
            name: featuredImage, 
            widget: image
            media_library: {
              config: {
                multiple: false,
                default_transformations: {
                  fetch_format: auto,
                  width: 2000,
                  height: 2000,
                  quality: auto,
                  crop: crop
                }
              } 
            } 
          - { label: Podtitulek, name: subtitle, widget: markdown, required: false }
          - { label: Obsah, name: body, widget: markdown }

      - file: 'content/pages/concerts.md'
        label: 'Koncerty'
        name: 'concerts-page'
        fields:
          - {
              label: Template,
              name: template,
              widget: hidden,
              default: ConcertsPage,
            }
          - { label: Slug, name: slug, widget: hidden, default: 'concerts' }
          - { label: Titulek, name: title, widget: string }
          - label: Obrázek v hlavičce, 
            name: featuredImage, 
            widget: image
            media_library: {
              config: {
                multiple: false,
                default_transformations: [ 
                    fetch_format: auto,
                    width: 2000,
                    height: 2000,
                    quality: auto,
                    crop: crop
                ]
              } 
            } 
          - label: 'Koncert'
            name: 'concerts'
            widget: 'list'
            required: false
            fields:
              - { label: 'Název koncertu', name: 'title', widget: 'string' }
              - { label: 'Popis koncertu', name: 'description', widget: 'string', required: false }

      - file: 'content/pages/records.md'
        label: 'Záznamy z koncertů'
        name: 'records-page'
        fields:
          - {
              label: Template,
              name: template,
              widget: hidden,
              default: RecordsPage,
            }
          - { label: Slug, name: slug, widget: hidden, default: 'records' }
          - { label: Titulek, name: title, widget: string }
          - label: 'Odkaz na youtube'
            name: 'links'
            widget: 'list'
            required: false
            fields:
              - { label: 'Odkaz', name: 'link', widget: 'string' }
  
  - name: posts
    label: Naše fotky
    editor:
      preview: true
    folder: content/posts
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - { label: Template, name: template, widget: hidden, default: SinglePost }
      - { label: Titulek, name: title, widget: string }
      - { label: Tag, name: tag, widget: string }
      - { label: Úvdní obrázek na kartě, name: featuredImage, widget: image }
      - { label: Datum / Pořadí, name: date, widget: date, format: 'YYYY-MM-DD' }
      - { label: Náhled textu na kartě, name: excerpt, widget: text, required: false }
      - { label: Obsah, name: body, widget: markdown, required: false }
      - label: "Galerie"
        name: "images"
        widget: "list"
        summary: '{{fields.image}}'
        fields:
          - {
              label: Obrázek/Obrázky, 
              name: gallery,
              widget: image,
              media_library: {
                config: {
                  multiple: true,
                  default_transformations: [
                    fetch_format: auto,
                    width: 2000,
                    height: 2000,
                    quality: auto,
                    crop: crop
                  ]
                } 
              }
          }